# Generated by Django 6.0.2 on 2026-02-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='region',
            new_name='regions_code_aa1ecb_idx',
            old_name='regions_reg_code_a5d06d_idx',
        ),
        migrations.AlterModelTable(
            name='region',
            table='regions',
        ),
    ]
