# Generated by Django 6.0.2 on 2026-02-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_rename_regions_reg_code_a5d06d_idx_regions_code_aa1ecb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='administrative_district_lvl_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='region',
            name='administrative_district_lvl_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
