repos:
  # Python code validation
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix"]
        stages: ["pre-commit"]
        types_or: [python, pyi]
      # Run the formatter.
      - id: ruff-format
        stages: ["pre-commit"]
        types_or: [python, pyi]
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: terraform-fmt
      - id: tflint
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.3
    hooks:
      # Update the uv lockfile
      - id: uv-lock
  # CircleCI validation
  - repo: local
    hooks:
      - id: circleci-validate-setup
        name: Validate CircleCI setup configuration
        stages: ["pre-commit"]
        language: system
        pass_filenames: false
        files: ^.circleci/config.yml$
        entry: circleci config validate .circleci/config.yml
  # Local type checking
  - repo: local
    hooks:
      - id: run-pyright
        stages: ["pre-push"]
        name: Run pyright
        entry: "uv run pyright ."
        language: system
        pass_filenames: false
  # Run tests if available
  - repo: local
    hooks:
      - id: run-pytest
        name: Run unit tests
        stages: ["pre-push"]
        language: system
        pass_filenames: false
        entry: uv run pytest tests
  # Markdown linting
  - repo: local
    hooks:
      - id: run-markdownlint
        name: Run Markdown linting
        stages: ["pre-commit"]
        language: system
        pass_filenames: false
        entry: markdownlint-cli2 --fix .
