repos:
  # Python code validation
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix"]
        stages: ["pre-commit"]
        types_or: [python, pyi]
      # Run the formatter.
      - id: ruff-format
        stages: ["pre-commit"]
        types_or: [python, pyi]
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.9.3
    hooks:
      # Update the uv lockfile
      - id: uv-lock
  # Local type checking
  - repo: local
    hooks:
      - id: run-pyright
        stages: ["pre-push"]
        name: Run pyright
        entry: "uv run pyright backend/"
        language: system
        pass_filenames: false
  # Run tests if available
  - repo: local
    hooks:
      - id: run-pytest
        name: Run unit tests
        stages: ["pre-push"]
        language: system
        pass_filenames: false
        entry: uv run pytest
  # Markdown linting
  - repo: local
    hooks:
      - id: run-markdownlint
        name: Run Markdown linting
        stages: ["pre-commit"]
        language: system
        pass_filenames: false
        entry: markdownlint-cli2 --fix .
