services:
  db:
    image: pgrouting/pgrouting:17-3.5-3.7.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-walkie}
      POSTGRES_USER: ${POSTGRES_USER:-walkie}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-walkie}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
