# Generated by Django 6.0.2 on 2026-02-25 13:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0003_region_administrative_district_lvl_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('segment_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField())),
                ('total_distance', models.FloatField()),
                ('is_loop', models.BooleanField(default=False)),
                ('start_point', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('end_point', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to='regions.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'region'], name='routes_user_id_5f7ed0_idx')],
            },
        ),
    ]
