# Generated by Django 6.0.2 on 2026-02-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
