# Generated by Django 6.0.2 on 2026-02-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_route_is_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='walked',
            field=models.BooleanField(default=False),
        ),
    ]
