# Generated by Django 6.0.2 on 2026-03-17 17:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_route_walked'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='custom_geometry',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
