# Generated by Django 6.0.2 on 2026-02-22 14:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('category', models.CharField(max_length=50)),
                ('surface', models.CharField(blank=True, max_length=50)),
                ('accessible', models.BooleanField(default=False)),
                ('is_lit', models.BooleanField(default=False)),
                ('region_code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paths', to='regions.region')),
            ],
            options={
                'indexes': [models.Index(fields=['region'], name='paths_path_region__0d2304_idx'), models.Index(fields=['category'], name='paths_path_categor_989d7f_idx'), models.Index(fields=['region_code'], name='paths_path_region__686a2a_idx')],
            },
        ),
    ]
