# Generated by Django 6.0.2 on 2026-02-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='path',
            new_name='paths_region__eedc14_idx',
            old_name='paths_path_region__0d2304_idx',
        ),
        migrations.RenameIndex(
            model_name='path',
            new_name='paths_categor_234f86_idx',
            old_name='paths_path_categor_989d7f_idx',
        ),
        migrations.RenameIndex(
            model_name='path',
            new_name='paths_region__37df2c_idx',
            old_name='paths_path_region__686a2a_idx',
        ),
        migrations.AlterModelTable(
            name='path',
            table='paths',
        ),
    ]
