# Generated by Django 6.0.2 on 2026-02-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0002_rename_paths_path_region__0d2304_idx_paths_region__eedc14_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='path',
            name='paths_region__37df2c_idx',
        ),
        migrations.RemoveField(
            model_name='path',
            name='region_code',
        ),
    ]
