# Generated by Django 6.0.2 on 2026-02-23 11:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0004_pgrouting_path_source_target'),
        ('regions', '0003_region_administrative_district_lvl_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='source',
        ),
        migrations.RemoveField(
            model_name='path',
            name='target',
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('source', models.IntegerField(blank=True, db_index=True, null=True)),
                ('target', models.IntegerField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('surface', models.CharField(blank=True, max_length=50)),
                ('accessible', models.BooleanField(default=False)),
                ('is_lit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to='regions.region')),
            ],
            options={
                'db_table': 'segments',
            },
        ),
        migrations.CreateModel(
            name='PathSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_segments', to='paths.path')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_segments', to='paths.segment')),
            ],
            options={
                'db_table': 'path_segments',
            },
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['region'], name='segments_region__3b3d12_idx'),
        ),
        migrations.AddIndex(
            model_name='segment',
            index=models.Index(fields=['category'], name='segments_categor_86507c_idx'),
        ),
        migrations.AddConstraint(
            model_name='pathsegment',
            constraint=models.UniqueConstraint(fields=('path', 'segment'), name='unique_path_segment'),
        ),
    ]
