# Generated by Django 6.0.2 on 2026-04-21 10:41

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0003_region_administrative_district_lvl_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('segment_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list)),
                ('walked_at', models.DateField()),
                ('distance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walks', to='regions.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'walks',
                'ordering': ['-walked_at', '-created_at'],
                'indexes': [models.Index(fields=['user', 'region'], name='walks_user_id_7ed3d8_idx'), models.Index(fields=['walked_at'], name='walks_walked__c90d2f_idx')],
            },
        ),
    ]
