# Generated by Django 6.0.2 on 2026-02-23 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0003_region_administrative_district_lvl_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='regions.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_regions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_regions',
                'constraints': [models.UniqueConstraint(fields=('user', 'region'), name='unique_user_favorite_region')],
            },
        ),
    ]
