# Generated by Django 6.0.2 on 2026-02-24 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paths', '0005_segment_pathsegment_remove_path_source_target'),
        ('regions', '0003_region_administrative_district_lvl_1_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PathWalkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('walked', 'Walked'), ('unwalked', 'Unwalked')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_logs', to='paths.path')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_walk_logs', to='regions.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_walk_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paths_walked',
                'indexes': [models.Index(fields=['user', 'region'], name='paths_walke_user_id_7e7bad_idx'), models.Index(fields=['user', 'path'], name='paths_walke_user_id_120615_idx'), models.Index(fields=['created_at'], name='paths_walke_created_ef7c53_idx')],
            },
        ),
    ]
