# Generated by Django 6.0.2 on 2026-03-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pathwalklog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pathwalklog',
            name='paths_walke_user_id_7e7bad_idx',
        ),
        migrations.RemoveIndex(
            model_name='pathwalklog',
            name='paths_walke_user_id_120615_idx',
        ),
        migrations.RemoveIndex(
            model_name='pathwalklog',
            name='paths_walke_created_ef7c53_idx',
        ),
        migrations.DeleteModel(
            name='PathWalkLog',
        ),
    ]
